### ISSUE TITLE
customHeaders field not recognised

### ISSUE THREAD

**Issue by harmanpa** [fjogeleit/http-request-action#10]
Using v1.3.2 with a ```customHeaders``` input I'm getting the following error:
```
##[warning]Unexpected input(s) 'customHeaders', valid inputs are ['url', 'method', 'contentType', 'data', 'username', 'password', 'timeout', 'bearerToken']
```

_Originally posted by @harmanpa in https://github.com/fjogeleit/http-request-action/issues/1#issuecomment-661667168_

**Comment by fjogeleit** [comment]
I added the customHeaders parameter to the list of allowed inputs. It should now work as expected. Thanks for reporting

**Comment by harmanpa** [comment]
Wow that was quick, thanks!
