### ISSUE TITLE
Enable mutual TLS https authentication

### ISSUE THREAD

**Issue by mysten-labs-charles-murphy** [fjogeleit/http-request-action#107]
Our servers sit behind teleport proxy (which enforces mutual TLS https). If this was written in python (by any chance), the python requests library already supports mutual TLS by allowing you to specify a client-side certificate and client-side CA. It would be quite trivial to support by exposing this option via the github action interface.

**Comment by fjogeleit** [comment]
It uses JS / Axios under the hood, not python but I will have a look.

**Comment by fjogeleit** [comment]
I added the `httpsCert` and `httpsKey` inputs to configure your cert and key file. With `httpsCA` you can configure the cert authority. Let me know if its not working as expected.

Its currently only available in the `main` branch / version. I will create an release if its working.

**Comment by mysten-labs-charles-murphy** [comment]
oh wow. that was fast. i will give it a go. thanks
