### ISSUE TITLE
Feature request: Not fail if no response was received

### ISSUE THREAD

**Issue by marcauberer** [fjogeleit/http-request-action#12]
Hi,
I have a feature request:
Wouldn't it be nice to have  a option to disable build failure, when no response, but a HTTP 200 status code was received as answer? Such as `disableFailureOnNoResponse` = true / false?

**Comment by fjogeleit** [comment]
Hey, for sure. I will have a look on it.

**Comment by fjogeleit** [comment]
Could you provide your received error message? In regular cases it should already work with success status code and no response body.

**Comment by marcauberer** [comment]
```
Run fjogeleit/http-request-action@master
  with:
    url: https://www.chillibits.com/src/build.php
    method: GET
    contentType: application/json
    data: {}
    timeout: 5000
##[error]{"error":"no response received"}
```

**Comment by fjogeleit** [comment]
You can try it out with the new Release v1.4.0. See the readme or release notes for details

https://github.com/fjogeleit/http-request-action/releases/tag/v1.4.0

**Comment by fjogeleit** [comment]
In many cases this error happens because of missing or incomplete response header. So the Action will show you a warning with the returned error but it will no longer fail with this new option

**Comment by marcauberer** [comment]
Thanks a lot! I will try it when I push the next time.
