### ISSUE TITLE
Feature Request: Mask responses

### ISSUE THREAD

**Issue by MikeFez** [fjogeleit/http-request-action#122]
Hello!

I have an endpoint I'm requesting via this action that returns sensitive information. This information (the entire response) should ideally be masked before being stored as an output, as if I were to attempt to mask it in a subsequent step, the step's "Run" dropdown (displayed via dropdown menu at the top of the step, such as the one seen [here](https://github.com/fjogeleit/http-request-action/actions/runs/7046855424/job/19179481357?pr=121#step:4:10)) ends up displaying the response in plain text as GitHub will inject contents of the step output directly into the logic before the step is even ran - this same logic including the line to mask the string upon running.

For example, this logic masks the response from a previous step w/ the id `secret-credentials`:
```
if [[ "$MASK_VARS" == "true" ]]; then
	echo "::add-mask::${{ steps.secret-credentials.outputs.response }}"
fi
```

However, when viewed via the "Run" dropdown after workflow completion, it appears similar to this:
```
if [[ "$MASK_VARS" == "true" ]]; then
	echo "::add-mask::{"t":"THIS_IS_A_SUPER_SECRET_STRING_THAT_SHOULD_NOT_BE_VISIBLE"}"
fi
```

I've used `responseFile` to store the output for the time being, which I can `cat` it into a variable in the post-request step. Doing it this way prevents the dropdown from showing the automatically-replaced step output, and since the response is then stored in a var populated from the file, I can then mask it without GH showing the output itself.

However, it would be nice for the action itself to be able to mask it upon receiving the response.

I've started implementing this [in a fork](https://github.com/MikeFez/http-request-action/compare/main...mf/feature/enable-output-masking). JS isn't exactly my strong suit, nor do I know what sort of testing is performed to validate the package in its entirety, but I figured I'd throw this here in case there's either any guidance you can give me to complete this feature, or if you'd like to use it as a base to complete it.

**Comment by MikeFez** [comment]
I've just edited the original description; after re-reviewing the content, it really lacked details. Regardless, sorry for throwing both of these your way on a Friday! Happy holidays!

**Comment by fjogeleit** [comment]
I prepared a branch you can try out.

`fjogeleit/http-request-action@response-mask`

It has a new input `maskResponse` which you can set to true to configure the response as secret which should it mask in your logs.

I also fixed the response file in case of an ignored status code.

**Comment by MikeFez** [comment]
Wow, thanks for the quick fix Frank!

Just tested it out:
- The response file fix is working; the file is not created if there's no response (which works for me), but better yet the step itself no longer failing
- maskResponse is working **perfectly**

This is killer, and allows me to seriously streamline my workflow now. Much appreciated!

**Comment by fjogeleit** [comment]
Thanks for your feedback, will release it today.

**Comment by fjogeleit** [comment]
Released as version `v1.15.0`, also available in `v1` or `main`

**Comment by fjogeleit** [comment]
@MikeFez just to let you no, the PR leaded to an breaking change with the response serialization which was not intended. I fixed this already but you might have to update your workflow with using the `fromJson` function around the output.

**Comment by MikeFez** [comment]
Roger that, thanks for the heads up and again for the quick fix!
