### ISSUE TITLE
Outputting a response via `responseFile` results in an exception when the response is empty.

### ISSUE THREAD

**Issue by MikeFez** [fjogeleit/http-request-action#123]
Hello!

I mentioned in [this issue](https://github.com/fjogeleit/http-request-action/issues/122) that in order to hide secrets, I'm storing responses in a `responseFile` which I later cat into a variable in a subsequent step in order to mask without GitHub displaying the contents, as it would with a step output.

The endpoint I'm trying to reach may or may not contain a response, which I use as a conditional for branching logic.

Unfortunately, when no response is returned while a responseFile is configured to be used, the action encounters an exception.

Example:
This action indicates the following `{"code":401,"message":""}`, the response itself being nothing at all.

I've set the following variables for the action (amongst credentials, data, method, other unrelated info):
- `ignoreStatusCodes: "401"`
- `preventFailureOnNoResponse: 'true'`
- `responseFile: 'http.response'`

However, the failure output of the step is as follows:
```
Warning: ignored status code: {"code":401,"message":""}
/opt/actions-runner/runner/_work/_actions/fjogeleit/http-request-action/v1.14.1/dist/index.js:5056
    let data = response.data
                        ^

TypeError: Cannot read properties of null (reading 'data')
    at /opt/actions-runner/runner/_work/_actions/fjogeleit/http-request-action/v1.14.1/dist/index.js:5056:25
    at /opt/actions-runner/runner/_work/_actions/fjogeleit/http-request-action/v1.14.1/dist/index.js:9886:26
    at Array.forEach (<anonymous>)
    at /opt/actions-runner/runner/_work/_actions/fjogeleit/http-request-action/v1.14.1/dist/index.js:9886:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by fjogeleit** [comment]
I’ll take a look on it

**Comment by MikeFez** [comment]
Thank you Frank!

**Comment by MikeFez** [comment]
Closing this out as the conversation in #122 encompasses the fix, currently contained within a dev branch.
