### ISSUE TITLE
Conditional  use of JSON.stringify on response.data causing issues parsing the response

### ISSUE THREAD

**Issue by imccausl** [fjogeleit/http-request-action#126]
First of all, thanks for your work in creating and maintaining this action!

In our CI workflow, we use this action to get a response from an API endpoint that returns a string. Previously, we parsed this response in the action.yml file with `fromJson`, but with [this change](https://github.com/fjogeleit/http-request-action/pull/124/files#diff-5b50710b2cf3b2af52a42cd4b9a0e62b9c28e2f25ffd0ff00b37b4d8aadde573R14-R16) an error is thrown. 

After a brief investigation, we discovered that it was `fromJson` that was choking on trying to parse a response that was no longer serialized and the solution is to remove the `fromJson` but it got me thinking: this is technically a breaking change for anyone using this with APIs that return a string response (a set of users that is probably, admittedly, very tiny though). Is there any benefit to conditionally serializing the response here? It seems that consumers that want to pass response data into other steps are forced to know ahead of time whether their endpoint is returning a string or an object so you can know whether to parse the response or not. Given this, would it be worth always serializing the response as before so that the response is always consistently parsable JSON?

We were able to fix our workflows fairly easily once the problem was understood, so I don't think I would really call this a bug. My motivation for posting this was just because I thought it was an interesting edge case that revealed something to think about in terms of how to handle the serialization of response data. Curious about your thoughts, but if you prefer to keep the change as is or that it doesn't warrant discussion or further thought, feel free to close this.

Tiny update: After taking a closer look at the documentation, if no change is deemed necessary it may warrant a change to the README since it does call out that `response` is a JSON string which is not necessarily true anymore.

<img width="411" alt="image" src="https://github.com/fjogeleit/http-request-action/assets/20084398/0273d060-234f-44b9-b9f0-0c3799578a72">

Happy to submit PRs for any changes, whether to the README or the code, but figured I'd wait to hear what you think first.

**Comment by fjogeleit** [comment]
Hey, thanks for investigation and support. A breaking change was not intended and I will have a look on it

**Comment by fjogeleit** [comment]
This PR should fix your issue and it should handle the response output as before

**Comment by imccausl** [comment]
Amazing! Thanks for the quick fix. Can confirm, back to working as expected with the `fromJson` applied to the response.

**Comment by fjogeleit** [comment]
Thanks a lot
