### ISSUE TITLE
Access to Response Body for Ignored Status Codes

### ISSUE THREAD

**Issue by KTSCode** [fjogeleit/http-request-action#140]
Currently, when a response returns one of the specified `ignoreStatusCodes`, the action's outputs (`response`, `headers`) are set to null. Although the response is logged as a warning, it is not accessible through any step outputs, limiting automated handling of these responses.

In workflows, especially those tied to CI/CD processes like PR reviews, having programmable access to these responses, even when they are intentionally ignored, is crucial. For instance, it would allow us to format the response and post it as a comment on the PR that triggered the workflow, enhancing automated feedback loops.

**Possible Solutions**:
1. **Always set `response` output**: Ensure the `response` output is set, regardless of the status code being part of the `ignoreStatusCodes`. This approach may introduce breaking changes for existing workflows expecting `null` values.
   
2. **Introduce a new output, e.g., `ignored_response`**: This output would specifically contain the response for ignored status codes, preserving the current behavior for the `response` output. This approach is preferable for backward compatibility and clearly distinguishes between standard and ignored responses, catering to various use cases without surprising existing users.

This enhancement would significantly improve the action's flexibility and utility in complex workflows, providing users with more options for handling different responses.

**Comment by fjogeleit** [comment]
Thanks for your feedback, I'll take a look. I think its more consistent to set always the response output if available.

**Comment by fjogeleit** [comment]
Response should now be set in cases where status code is ignored
