### ISSUE TITLE
'No response received' is logged when server returns just a status code

### ISSUE THREAD

**Issue by grb48** [fjogeleit/http-request-action#141]
If preventFailureOnNoResponse is set and the server returns a 2XX status code, then the 'no response received' should not occur (or not shown in the output)

::warning::no response received: {"message":"timeout of 5000ms exceeded","name":"AxiosError","stack":"AxiosError: timeout of 5000ms exceeded\n    at RedirectableRequest.handleRequestTimeout (/run/act/actions/fjogeleit-http-request-action@v1/dist/index.js:32459:16)\n    at RedirectableRequest.emit (node:events:519:28)\n    at Timeout.<anonymous> (/run/act/actions/fjogeleit-http-request-action@v1/dist/index.js:2840:12)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"adapter":["xhr","http"],"transformRequest":[null],"transformRespon....... </snip>

Also, thank you for such a great tool!

**Comment by fjogeleit** [comment]
As you notice in the error, you have a timeout error, in cases where you have this warning the action doesn't receive a response and also no status code it could check.
