### ISSUE TITLE
The "status"-output is not supplied by the action

### ISSUE THREAD

**Issue by Kbonheur** [fjogeleit/http-request-action#150]
This is quite breaking for my use-case as I need this to check the HTTP-statuscode in the next step of my workflow.
Is there another way to retrieve the HTTP-statuscode?

**Comment by fjogeleit** [comment]
I will take a look

**Comment by fjogeleit** [comment]
Which version do you use? Its maybe not in a release yet.

**Comment by Kbonheur** [comment]
Hi  @fjogeleit: I'm using version v1.15.5. I noticed that in the action.yml of the project the output is not specified which explained why I always got a blanc value for the "status"-output.
Thx for your quick reply.

**Comment by fjogeleit** [comment]
Okay, you can use main for now, I will create a new release today.

**Comment by Kbonheur** [comment]
This issue was solved with #151 
Is it possible to provide a new tag for this version please?
Thank you for your support.
