### ISSUE TITLE
Job failed with "version `GLIBC_2.28' not found "

### ISSUE THREAD

**Issue by saravanan-uthirapathy-kr** [fjogeleit/http-request-action#153]
I am using fjogeleit/http-request-action@v1 on self-hosted runner, the job is failing and throwing 
/home/vsts-agent/actions-runner/externals/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version **`GLIBC_2.28' not found** (required by /home/vsts-agent/actions-runner/externals/node20/bin/node)
Any advice on this issue?
related issue on a forum:
https://github.com/actions/runner/issues/2906

**Comment by fjogeleit** [comment]
Hi, sorry not really. You could try to use v1.5.1 which was the latest version that used node16.
