### ISSUE TITLE
http-request to HTTPS endpoint fails with no response received.

### ISSUE THREAD

**Issue by ajgerace** [fjogeleit/http-request-action#166]
Attempting to use http-request-action v1 to retrieve a secure endpoint.  the action fails with an error '::error::{"error":"no response received"}'.  If I switch to an HTTP endpoint the request succeeds. 

i am testing with GITEA v1.22 and gitea_runner v0.2.11. 
This request works
`
           uses: fjogeleit/http-request-action@v1
            with:
               url: 'http://10.1.20.3:8080/'
               method: 'GET'
               customHeaders: '{"Content-Type": "application/json"}'
`

This request provides the error above:
`
           uses: fjogeleit/http-request-action@v1
            with:
               url: 'https://site.example.com/'
               method: 'GET'
               customHeaders: '{"Content-Type": "application/json"}'
`
I've confirmed I have valid a TLS certificate that matches site '*.example.com'  Does http-request-action support sites that utilize wildcard certificates?

**Comment by ajgerace** [comment]
I resolved this issue by setting ignoreSsl: true.

**Comment by SMJSGaming** [comment]
I have the same error but ignoreSsl isn't a valid fix if you ask me. It seems that this action can't handle cloudflare proxies
