### ISSUE TITLE
Unable to convert Data and Files into FormData: data is not defined

### ISSUE THREAD

**Issue by SMJSGaming** [fjogeleit/http-request-action#168]
It seems I encountered an internal issue with multipart/form-data. Whenever I try using it I get `{"message":"Unable to convert Data and Files into FormData: data is not defined","data":{},"files":{"bin":"/home/runner/work/_actions/geode-sdk/build-geode-mod/main/combine/out/smjs.gdintercept.geode"}}`. Suggesting a variable is being used which isn't defined.

**Comment by fjogeleit** [comment]
I take a look

**Comment by fjogeleit** [comment]
I updated the main branch, you should now get the correct error message

**Comment by SMJSGaming** [comment]
Now I get `{"message":"Unable to convert Data and Files into FormData: formData.forEach is not a function","data":{},"files":{"bin":"/home/runner/work/_actions/geode-sdk/build-geode-mod/main/combine/out/smjs.gdintercept.geode"}}`

**Comment by SMJSGaming** [comment]
So based on the last commit, it seems formData is undefined or null

**Comment by fjogeleit** [comment]
hm the used implementation does no support forEach. I removed it, should display another error now

**Comment by SMJSGaming** [comment]
Still the same error, I don't see the forEach removed in the main branch either

**Comment by fjogeleit** [comment]
my bad, did not build my change .. sorry

**Comment by SMJSGaming** [comment]
Weird, getting a no such file error, it should exist so I'll double check if I didn't miss anything. I'll provide the full error for context:
```
Error: {"message":"Unable to read Content-Length: ENOENT: no such file or directory, stat '/home/runner/work/_actions/geode-sdk/build-geode-mod/main/combine/out/smjs.gdintercept.geode'"}
Error: {"message":"Cannot read properties of undefined (reading 'headers')","data":{"_overheadLength":177,"_valueLength":0,"_valuesToMeasure":[{"fd":null,"path":"/home/runner/work/_actions/geode-sdk/build-geode-mod/main/combine/out/smjs.gdintercept.geode","flags":"r","mode":438,"end":null,"bytesRead":0,"_events":{},"_readableState":{"highWaterMark":65536,"buffer":[],"bufferIndex":0,"length":0,"pipes":[],"awaitDrainWriters":null},"_eventsCount":3}],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":false,"_streams":["----------------------------660643427582859988957989\r\nContent-Disposition: form-data; name=\"bin\"; filename=\"smjs.gdintercept.geode\"\r\nContent-Type: application/octet-stream\r\n\r\n",{"source":{"fd":null,"path":"/home/runner/work/_actions/geode-sdk/build-geode-mod/main/combine/out/smjs.gdintercept.geode","flags":"r","mode":438,"end":null,"bytesRead":0,"_events":{},"_readableState":{"highWaterMark":65536,"buffer":[],"bufferIndex":0,"length":0,"pipes":[],"awaitDrainWriters":null},"_eventsCount":3},"dataSize":0,"maxDataSize":null,"pauseStream":true,"_maxDataSizeExceeded":false,"_released":false,"_bufferedEvents":[{"0":"pause"},{"0":"error","1":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/home/runner/work/_actions/geode-sdk/build-geode-mod/main/combine/out/smjs.gdintercept.geode"}},{"0":"close"}],"_events":{},"_eventsCount":1},null],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------660643427582859988957989"}}
```

**Comment by SMJSGaming** [comment]
Alright, seems to have been an issue of rerunning a failed job to test this. Right now getting errors from my server side so that's a step in the right direction. Thanks for the support
