### ISSUE TITLE
Upload a file [Question]

### ISSUE THREAD

**Issue by paolorevillosa** [fjogeleit/http-request-action#19]
Hi!, is there a way to upload file using this action? Im new to github actions and i was looking way to upload my artifacts on my website. Thanks

**Comment by fjogeleit** [comment]
Hey @paolorevillosa, it is not possible yet. For this feature it has to load the file inside of the action to send it with axios. I will have a look on it if I can provide it. But it looks like that this action can help you: https://github.com/marketplace/actions/upload-file-action

**Comment by paolorevillosa** [comment]
Thanks, gonna wait for your enhancement but for now, im gonna look at the repository that you gave

**Comment by fjogeleit** [comment]
File Uploaded is provided with the latest version 1.7.0
