### ISSUE TITLE
DirectApiRequestHasMoreThanOneAuthorization Error

### ISSUE THREAD

**Issue by isaacrlevin** [fjogeleit/http-request-action#2]
Whenever I try to post to an Azure Logic App, I get this message

> ##[error]{"message":{"error":{"code":"DirectApiRequestHasMoreThanOneAuthorization","message":"The request has both SAS authentication scheme and 'Basic' authorization scheme. Only one scheme should be used."}}}

I can confirm I can post to this url from PostMan with no issue, here is my input

```
    url: ***
    method: POST
    contentType: application/json
    data: { "url": "http://isaaclevin.com/about" }
    timeout: 5000
```

With logic apps, the auth is in the url, so I do not supply a Bearer or Basic Auth. I have a feeling that since I am not supplying either, the http request looks odd.

**Comment by fjogeleit** [comment]
I fixed the issue by only adding the auth config to axios if configured. Hope this fix your issue.
