### ISSUE TITLE
Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by paolorevillosa** [fjogeleit/http-request-action#22]
I was trying to upload a generated APK on my webserver. I do not have issue when i trying to upload a small size apk but when there is a large size of file it gives a error. I also attached screenshot for the logs

![image](https://user-images.githubusercontent.com/29852199/108487081-ceec6280-72d9-11eb-8101-42c583189012.png)

**Comment by fjogeleit** [comment]
Thanks for report. I will check this

**Comment by fjogeleit** [comment]
Can you test the action with the new version v1.7.2 to verify that it is working for you now?

**Comment by paolorevillosa** [comment]
Same result for latest version 

![image](https://user-images.githubusercontent.com/29852199/108494566-a87ef500-72e2-11eb-8465-20860102524b.png)

**Comment by fjogeleit** [comment]
Sorry, my mistake - I forgot to build the action the changes. I build my changes and tagged a v1.7.3 - the changes should now applied and working.

**Comment by paolorevillosa** [comment]
Its now work for me!! Thanks a lot

**Comment by fjogeleit** [comment]
Great, thanks for reporting.
