### ISSUE TITLE
feature request: skip even if the route returns an error, 404, or otherwise

### ISSUE THREAD

**Issue by seiyria** [fjogeleit/http-request-action#25]
Ran into a bit of a situation: I created a new route and tried to deploy it, my action _would_ hook into this, but instead it got a 404 since it wasn't deployed yet! Would be nice to skip caring about a 404 or other errors as it's mostly a notification endpoint.

**Comment by fjogeleit** [comment]
Hey, thanks for your request. So your goal is no failing Workflow if the action fails?

Maybe then you should have a look on this configuration:

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions

Let me know if you have another use case for this problem. Maybe I could implement some kind of status code ignoreList.

**Comment by seiyria** [comment]
Yeah, I want to basically always pass even if this action fails since it's basically pinging and saying the service is rebooting. If it fails it doesn't need to block.

I can't make it always pass on fail because I have other build tasks that must fail and abort, so having a status code option would be best, or even better that as well as an option to ignore all errors (otherwise I'd have to figure out what error codes to ignore beforehand).

**Comment by seiyria** [comment]
Looks like it works, thanks!

**Comment by fjogeleit** [comment]
Glad to hear, thanks for your feedback.
