### ISSUE TITLE
Passing a JSON string to data

### ISSUE THREAD

**Issue by paolorevillosa** [fjogeleit/http-request-action#28]
Hi! as mention on the title, i was trying to upload a json string but i everytime i add the json string to data, my other variables were undefined on my api

Here is my sample logs

`[{"message":"t-12-test"}, {"message":"b-13-test"}]`

**Comment by fjogeleit** [comment]
Hey, what do you mean with other variables? 
Do you use data together with files?

How your data looks like?

**Comment by paolorevillosa** [comment]
my data looks like this

`data: '{"product":"1","description": "${{ github.event.inputs.description }}", "logs": "${{ steps.logs.outputs.logs-on-json }}"}'`

where the steps.logs.outputs.logs-on-json returns a string on json format

**Comment by fjogeleit** [comment]
Okay and what is your concrete problem? You said that variables are undefined, which ones exactly?

**Comment by paolorevillosa** [comment]
can i just close it? I found workaround for my issue.

the issue when you have a " character to pass on data just like in json format (`[{"message":"t-12-test"}, {"message":"b-13-test"}]`), all my data variables is missing, i guess there is a error getting data from **data** because of (")

the data will look like this
`data: {"product":"1","description": "", "logs": "[{"message":"t-12-test"}, {"message":"b-13-test"}]}`

**Comment by fjogeleit** [comment]
Okay, if it works now I'm happy. If you need help further let me now.
