### ISSUE TITLE
Can't add token manually to Authorization header in customHeaders

### ISSUE THREAD

**Issue by stephanos7** [fjogeleit/http-request-action#29]
Hey, i keep getting _Unsupported Format for Authorization_ header when i try to send a token via customHeaders (I can't use the bearerToken property because i get _Authorization Header Missing_ in that case). It's probably something with my json format but can't figure out what exactly. The Authorization header appears empty in the logs. I've tested this is postman and the request goes through correctly. Any pointers?

### My action:

`      - name: HTTP Request Action
        id: getAuth0AccessToken
        uses: fjogeleit/http-request-action@v1.8.0
        with:
          url: <<removed by author>>
          data: <<removed by author>>
      - name: Show Token Response
        run: echo ${{ steps.getAuth0AccessToken.outputs.response }}
      - name: HTTP Request Action
        id: callNetlifyFunction
        uses: fjogeleit/http-request-action@v1.8.0
        with:
          url: <<removed by author>>
          customHeaders: '{"Authorization":"Bearer ${{steps.getAuth0AccessToken.outputs.response.access_token}}"}'
      - name: Show L Response
        run: echo ${{ steps.callNetlifyFunction.outputs.response }}`

### the log response: 

[debug]steps.callNetlifyFunction.outputs.requestError='{"message":"Request failed with status code 401","name":"Error","stack":"Error: Request failed with status code 401\n    at createError (/home/runner/work/_actions/fjogeleit/http-request-action/v1.8.0/dist/index.js:71:15)\n    at settle (/home/runner/work/_actions/fjogeleit/http-request-action/v1.8.0/dist/index.js:3108:12)\n    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/fjogeleit/http-request-action/v1.8.0/dist/index.js:3552:11)\n    at IncomingMessage.emit (events.js:215:7)\n    at endReadableNT (_stream_readable.js:1184:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"method":"post","data":"{}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json",**"Authorization":""**,"User-Agent":"axios/0.21.1","Content-Length":2},"baseURL":<removed by author>,"transformRequest":[null],"transformResponse":[null],"timeout":5000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":null,"maxBodyLength":null}}

**Error: {"code":401,"message":{"error":"invalid_header","error_description":"Unsupported format for the Authorization header"}}`**

**Comment by fjogeleit** [comment]
Hey, die you test that ${{steps.getAuth0AccessToken.outputs.response.access_token}} returns a token as expected? Your error Boy using the bearerToken property indicates That this value is properly empty.

**Comment by stephanos7** [comment]
Yes, you are right thanks, that's empty indeed. I do get the token from the previous job but I probably need to store it in a variable before using in the second job i guess - i'm new to github actions so will read a bit on that.
