### ISSUE TITLE
JSON object being wrapped in additional string

### ISSUE THREAD

**Issue by Jernik** [fjogeleit/http-request-action#32]
I'm trying to call an endpoint that expects a body of 
`{"config":"<yaml string>"}`
this is how I am calling this action:
``` - name: HTTP Request Action
        # You may pin to the exact commit or the version.
        # uses: fjogeleit/http-request-action@8e939c608aea2d5df19da3e8229cf035f7aa9e4c
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          # Request URL
          url: "https://api.jernik.me/guilds/361634430626037770/config"
          # Request Method
          method: "POST"
          # Content Type
          contentType: "application/json"
          # Request Body as JSON String
          data: "{\"config\": \"${{steps.read_file.outputs.contents}}}\"}"
          # Custom HTTP Headers
          customHeaders: "{\"X-Api-Key\": \"${{ secrets.zeppelin_apikey }}\"}"
```

this is producing a body of 
`body: '"{\\"config\\": \\"<yamlstring>\\"}"'`
This is an extra layer of json stringification and I cannot figure out how to tell this action "just use the body I'm giving you, don't stringify it more"

**Comment by fjogeleit** [comment]
Hey, it Looks like that axios is not able to parse your JSON. Did you try single quotes in the json? Maybe your yaml includes quotes which makes the JSON invalid.

**Comment by Jernik** [comment]
I ended up just moving to a cURL based solution running in a `run` action, I haven't had time to troubleshoot this one! I can provide any extra information you need if you want to, but I have moved on from using this action, sorry

**Comment by fjogeleit** [comment]
Okay, that’s fine. Then I close this issue
