### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Oktopuce** [fjogeleit/http-request-action#35]
Hi,
I suggest you to improve the documentation because I struggle some hours before understanding the problem with a POST request and data as  key=value pairs, I had to set : 

`contentType: application/x-www-form-urlencoded`

but it's not obvious in documentation, may be you can change it like this :

`Request Body Content as JSON String (or key=value pairs separated by '&' and contentType: application/x-www-form-urlencoded), only for POST / PUT / PATCH Requests`

**Comment by fjogeleit** [comment]
Hey sorry that you had this issue. I will add this suggestion and try to improve it in general when I find some time.

**Comment by Oktopuce** [comment]
In fact, it's not just a documentation issue, there is also a bug because POST data received are like this : 

`{"{\"my_data\":\"the_value\"}":""}`

and should be like this : 

`{{"my_data":"the_value"}}`

It seems that there is a double JSON encode.

**Comment by fjogeleit** [comment]
The action itself does no json encoding. There are sometimes issues by the github yaml parser of the action. How does your data value looks like in your workflow? You can try to define it inside of single quotes:

```yaml
data: '{"my_data":"the_value"}'
```

**Comment by Oktopuce** [comment]
The action is defined like this : 

      - name: Make Request
        uses: fjogeleit/http-request-action@master
        with:
          method: 'POST'
          contentType: application/x-www-form-urlencoded
          url: "https://the_url"
          data: '{"my_data": "the_value"}'

**Comment by fjogeleit** [comment]
what do your backend expect? If your content is  json the contentType should be "application/json". If the backend expect application/x-www-form-urlencoded your data should look like

`data: ' my_data = the_value'`

**Comment by Oktopuce** [comment]
With this it works as expected so you should improve the documentation.

But I never succeeded to receive data when I don't set contentType=application/x-www-form-urlencoded.
Without this option I never received the POST data.

Thanks for your help.

**Comment by fjogeleit** [comment]
I already added your suggestion. Thank you

I think this depends on your Backend/Service. I am using only JSON, so I have not much experience with the other formats. The hint with the 'my_data=the_value' was also a contribution.

Let me now if you encounter any other problems.
