### ISSUE TITLE
Bookkeeping request: rename default branch

### ISSUE THREAD

**Issue by estherkim** [fjogeleit/http-request-action#40]
Hi, a bit of bookkeeping, but have you considered renaming the default branch away from `master`?

Some context - https://github.com/github/renaming

Thanks!

**Comment by fjogeleit** [comment]
Hey @estherkim, thanks for your request. Currently I am mainly maintaining this action and extending it based on user feedback.

I am open to change it and will try to find some time in the near future for this.

**Comment by fjogeleit** [comment]
The new default branch is `main`. The `master` branch is still available to not break existing workflows but is marked as deprecated.

**Comment by estherkim** [comment]
Works for me, thank you!
