### ISSUE TITLE
Action step fails if the post request response is null

### ISSUE THREAD

**Issue by rajatrj16** [fjogeleit/http-request-action#44]
If the post request response is null but the request is pass it should not fail
```Error: {"error":"no response received"}```

**Comment by fjogeleit** [comment]
Hey @rajatrj16, can you please try to set the input option `preventFailureOnNoResponse` to `true` as described in the readme?

**Comment by rajatrj16** [comment]
Ahh yeah - I checked it later on other issues https://github.com/fjogeleit/http-request-action/releases/tag/v1.4.0
You might want to add that in response section of the readme as well :smile: 
Thanks

**Comment by rajatrj16** [comment]
```
Run fjogeleit/http-request-action@v1.4.0
  with:
    url: https://sonarqube.XXXX.zone/api/qualitygates/select
    method: POST
    username: ***
    data: {projectKey=${params.SERVICE_NAME}&gateName=QGProd}
    preventFailureOnNoResponse: true
    contentType: application/json
    timeout: 5000
  env:
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.15-10/x6[4](https://github.com/OpenGov/sonarqube-testing-project/runs/6320161046?check_suite_focus=true#step:8:4)
    GRADLE_BUILD_ACTION_CACHE_RESTORED: true
    SONAR_TOKEN: ***
Error: Unexpected token p in JSON at position 1
```

**Comment by fjogeleit** [comment]
Your data part doesn't look like a valid JSON string

**Comment by fjogeleit** [comment]
> Ahh yeah - I checked it later on other issues https://github.com/fjogeleit/http-request-action/releases/tag/v1.4.0 You might want to add that in response section of the readme as well 😄 Thanks

Thanks for your feedback. I will check if I can improve the readme.
