### ISSUE TITLE
Let's Encrypt SSL issue

### ISSUE THREAD

**Issue by dei79** [fjogeleit/http-request-action#48]
I try to use this extension with a backend configured with a Let's Encrypt certificate:

```code
- name: Triggering WebHool
   uses: fjogeleit/http-request-action@v1
   with:
      url: 'https://my-letsencryptdomain/xxx'
      method: 'POST'
```

The result is always

Warning: ***"message":"unable to verify the first certificate","name":"Error","stack":"Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\n    at TLSSocket.emit (node:events:390:28)\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)","config":***"method":"post","data":"***","headers":***"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.21.4","Content-

Do you have any ideas what I can do?

**Comment by fjogeleit** [comment]
Hey, as far as I could find it is needed to provide your CA to get it work in a secure way. This is currently not possible but I will have a look and add a input to make it possible.

**Comment by fjogeleit** [comment]
You can use the new version v1.10.0 to add your CA via the new `httpsCA`. You can provide it as secret in your GH Workflow

**Comment by fjogeleit** [comment]
I close the issue for know, let me know if you still need additional help.
