### ISSUE TITLE
a way to mask the response data

### ISSUE THREAD

**Issue by jamesla** [fjogeleit/http-request-action#55]
I want to send back a secret value and don't want it visible to anybody that clicks on the actions tab for the repository. Is there any way to make the mask the post data?

IE assume "world" is secret - i'd want that masked or just the data not output here altogether.

![image](https://user-images.githubusercontent.com/5243178/190028909-c3c2c2c1-660a-4029-85cd-a7928bdb28d4.png)

**Comment by fjogeleit** [comment]
Hey, is your secret a constant value? Then you can persist it as action secret and reference the secret key. This way it will not be visible in the output of the action.

**Comment by jamesla** [comment]
Unfortunately no - it's generated dynamically.

**Comment by jamesla** [comment]
actually turns out you can use   `echo "::add-mask::$var"` and it will mask your variable in this step (showing ***)

Cheers!

**Comment by fjogeleit** [comment]
Great, thanks for your reply.
