### ISSUE TITLE
Unable to convert Data and Files into FormData

### ISSUE THREAD

**Issue by roblack** [fjogeleit/http-request-action#57]
Not sure if I am missing something in the setup, regular posts requests work great, but when I try to upload a file, in this case .IPA file, I get this error (I get it no matter the file type actually)

```
{"message":"Unable to convert Data and Files into FormData: data is not defined","data":{},"files":{"file":"<WORKSPACE>/test.ipa"}}
```

**Comment by fjogeleit** [comment]
Is your request method set to GET?

**Comment by roblack** [comment]
No. It is set to POST, although it is POST by default as well right?

**Comment by fjogeleit** [comment]
yes, default is POST.

**Comment by fjogeleit** [comment]
can you please remove the empty data input, so it can fallback to the default.

**Comment by roblack** [comment]
Will do that now for safe measure, but I actually added it thinking it needed some input 😅

Still the same response:
```
{"message":"Unable to convert Data and Files into FormData: data is not defined","data":{},"files":{"file":"....
```

**Comment by fjogeleit** [comment]
hm okay, strange, I will have a look on it.

**Comment by fjogeleit** [comment]
I published a new version with a fix and new testcase. Can you try if its now working?

**Comment by roblack** [comment]
will do right now 🙌

**Comment by roblack** [comment]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/21968377/194136296-c44cbfd0-e682-43a3-81ef-07264c8a8649.png">
 
🙌

I had some issues at first tho, but tried numerous setups and kept getting the same error. So I thought the location was not picked up properly or something. 

In the end when I used the complete path, it worked! 🙌 
I will investigate further what's up with the path, but I had the file in root 🤷‍♂️

Main thing is, action is working like a charm! Thank you!

**Comment by fjogeleit** [comment]
thanks a lot for your feedback and reporting the issue, great that my action can help you.
