### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by roblack** [fjogeleit/http-request-action#59]
After trying to upload the IPA file, which is 131mb. I got the message/error below.

I should also increase the `timeout` to something which would allow it plenty of time for upload as well I guess, but is there a hard limit at the moment for the amount of data one can upload?

Error: {"code":413,"message":"<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"}

**Comment by roblack** [comment]
The endpoint I am reaching out to is not under my control, but I will get in touch with them to see what's up then.
Doing another test soon 🤞
Thank you! 🙌

**Comment by fjogeleit** [comment]
Your welcome. So I close this issue for now.
