### ISSUE TITLE
request sent successfully. no response displayed. error message

### ISSUE THREAD

**Issue by dittolooch** [fjogeleit/http-request-action#6]
hi,
the action sent the post request successfully but there's no response displayed. also seen the error message below:

(node:2444) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'code' of undefined
    at /home/runner/work/_actions/fjogeleit/http-request-action/master/dist/index.js:2656:58
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fjogeleit** [comment]
I updated the error handling, so you should know get detailed information why the API call is rejected.
