### ISSUE TITLE
Error passing github commit message

### ISSUE THREAD

**Issue by alexhibernian** [fjogeleit/http-request-action#71]
Have been using this for a while now and it has been working great but since today it seems something is not allowing the github message to be passed as its breaking the data string. 

      - name: 'OPTIK Patch POST API'
        uses: 'fjogeleit/http-request-action@main'
        with:
          url: 'myurl'
          method: 'POST'
          bearerToken: ${{ secrets.PATCH_BEARER }}
          timeout: 15000
          contentType : 'application/x-www-form-urlencoded'
          customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
          data: 'completed=N&version=${{ steps.version-bump.outputs.newTag }}&commitMessage=${{ github.event.head_commit.message }}&addedWhen=${{ steps.date.outputs.date }}&committedBy=${{ github.event.head_commit.author.name }}&system=OptikPMS'
 
 My api is responding with the values are required so completed is required and so on. 
 the commit runs across multiple lines as have many others yet today its just not working

**Comment by fjogeleit** [comment]
Hey, thanks. I have an idea what the issue could be. You can use @v1 as version tag which should still work as before.

**Comment by fjogeleit** [comment]
I merged a fix, please let me know if you still have issues

**Comment by fjogeleit** [comment]
@alexhibernian do you have feedback if it is working again?

**Comment by alexhibernian** [comment]
@fjogeleit That is working again thank you.
