### ISSUE TITLE
v1 is not pointing to the latest v1.x.x version

### ISSUE THREAD

**Issue by fabasoad** [fjogeleit/http-request-action#77]
## Actual behavior

Currently the latest version is [v1.12.0](https://github.com/fjogeleit/http-request-action/releases/tag/v1.12.0) that points to 86014825e97036cd3e0903bbc72b3c5fff7474c4 (released on 2022/11/07) but [v1](https://github.com/fjogeleit/http-request-action/releases/tag/v1) points to fd5cf60c69049efb1397207cc8b442709a869685 (released on 2022/10/06).

## Expected behavior

Both [v1.12.0](https://github.com/fjogeleit/http-request-action/releases/tag/v1.12.0) and [v1](https://github.com/fjogeleit/http-request-action/releases/tag/v1) should point to 86014825e97036cd3e0903bbc72b3c5fff7474c4. And going forward `v1` should point to the latest `v1.x.x`. Ideally `v1.1` should point to the latest `v1.1.x`, etc.

**Comment by fjogeleit** [comment]
thanks for reporting. I updated the v1 tag to v1.12.0

**Comment by fabasoad** [comment]
@fjogeleit Thanks for prompt reaction! I would recommend you to take a look at [this](https://github.com/marketplace/actions/tagger-move-semantic-tags) GHA. It's super easy to use and it does all these tagging work automatically. Just FYI, maybe you will find it useful :)

**Comment by fjogeleit** [comment]
thanks a lot for the tip. I will check it out.
