### ISSUE TITLE
Feature Request: store response into a file 

### ISSUE THREAD

**Issue by hotzen** [fjogeleit/http-request-action#82]
Hello, thanks a bunch for the action.
I need to instrument an HTTP API that yields a multi-megabyte `outputs.response` and then store this response as an artifact using `actions/upload-artifact@v3` which is based on files.

So currently I have to have an intermediate step `run: echo "${{ steps.fetch-messages.outputs.response }}" > messages.json` to store the response into a file, before I pass it on to `actions/upload-artifact@v3`.

Could you introduce another property like `storeResponseIntoFile: response.json` that directly stores the raw-response into a file?

**Comment by fjogeleit** [comment]
Hey,  sorry for the late response.

I will have a look on it in the next days - when I find some time.

**Comment by fjogeleit** [comment]
@hotzen @NeutrinoLiu with the new release `v1.13.0` exists a new input value `responseFile`  to specify a file path which will be used to persist the response to your request.

**Comment by fjogeleit** [comment]
You can checkout https://github.com/fjogeleit/http-request-action/blob/main/.github/workflows/ci.yml#L135 as example
