### ISSUE TITLE
Retries?

### ISSUE THREAD

**Issue by djdylan2000** [fjogeleit/http-request-action#95]
What are your thoughts on adding a retry count and implementing either exponential backoff or even linear backoff, given that networks are never 100% reliable?

**Comment by fjogeleit** [comment]
Hey, thanks for your request, in general you could use an action like `Wandalen/wretry.action@master` to implement a retry mechanism.

I will check if I can implement something directly but it can take some time. Some stuff to do right now.

**Comment by fjogeleit** [comment]
With the new release you have a retry and retryWait input to configure how often a request should be retried and the wait time between each request.

**Comment by djdylan2000** [comment]
> With the new release you have a retry and retryWait input to configure how often a request should be retried and the wait time between each request.

Awesome! Thanks for implementing it so quickly!
